### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by olivernybroe** [nfc-tools/libndef#3]
Getting the following error when trying to compile in windows 10.
`error: variable 'QDataStream stream' has initializer but incomplete type
                         QDataStream stream(record.payload());
                                            ^`

**Comment by neomilium** [comment]
Which Qt version do you use ?

Nobody in our team uses Windows, can you provide a patch ?

**Comment by uruloke** [comment]
Oh I am sorry, totally forgot to give that infromation. 
I am using Qt 5.5.0 with a MinGW 32-bit compiler

**Comment by travisgoodspeed** [comment]
I've provided a patch in #5.  Tested on Debian/Testing with G++ 8.

**Comment by doegox** [comment]
patch merged
